return {
	-- 	"nvim-telescope/telescope.nvim",
	-- 	dependencies = {
	-- 		"nvim-lua/plenary.nvim",
	-- 		{
	-- 			"nvim-telescope/telescope-live-grep-args.nvim",
	-- 			-- This will not install any breaking changes.
	-- 			-- For major updates, this must be adjusted manually.
	-- 			version = "^1.0.0",
	-- 		},
	-- 	},
	-- 	config = function()
	-- 		local telescope = require("telescope")
	--
	-- 		local opts = {
	-- 			defaults = {
	-- 				mappings = {
	-- 					i = {
	-- 						["<C-Space>"] = require("telescope.actions").to_fuzzy_refine,
	-- 					},
	-- 				},
	-- 			},
	-- 			extensions = {
	-- 				live_grep_args = {
	-- 					auto_quoting = true, -- enable/disable auto-quoting
	-- 					-- define mappings, e.g.
	-- 					mappings = { -- extend mappings
	-- 						i = {
	-- 							["<C-k>"] = require("telescope-live-grep-args.actions").quote_prompt(),
	-- 							["<C-i>"] = require("telescope-live-grep-args.actions").quote_prompt({
	-- 								postfix = " --iglob ",
	-- 							}),
	-- 							-- freeze the current list and start a fuzzy search in the frozen list
	-- 							["<C-space>"] = require("telescope-live-grep-args.actions").to_fuzzy_refine,
	-- 						},
	-- 					},
	-- 				},
	-- 			},
	-- 		}
	--
	-- 		telescope.setup(opts)
	--
	-- 		telescope.load_extension("live_grep_args")
	-- 	end,
	-- 	keys = {
	-- 		-- Basic
	-- 		{
	-- 			"<leader> ",
	-- 			function()
	-- 				require("telescope.builtin").find_files()
	-- 			end,
	-- 		},
	-- 		{
	-- 			"<leader>/",
	-- 			function()
	-- 				require("telescope").extensions.live_grep_args.live_grep_args()
	-- 			end,
	-- 		},
	-- 		{
	-- 			"<leader>sb",
	-- 			function()
	-- 				require("telescope.builtin").buffers()
	-- 			end,
	-- 		},
	-- 		{
	-- 			"<leader>sq",
	-- 			function()
	-- 				require("telescope.builtin").quickfix()
	-- 			end,
	-- 		},
	-- 		{
	-- 			"<leader>sj",
	-- 			function()
	-- 				require("telescope.builtin").jumplist()
	-- 			end,
	-- 		},
	-- 		-- LSP
	-- 		{
	-- 			"<leader>cu",
	-- 			function()
	-- 				require("telescope.builtin").lsp_references()
	-- 			end,
	-- 		},
	-- 		{
	-- 			"<leader>ci",
	-- 			function()
	-- 				require("telescope.builtin").lsp_incoming_calls()
	-- 			end,
	-- 		},
	-- 		{
	-- 			"<leader>co",
	-- 			function()
	-- 				require("telescope.builtin").lsp_outgoing_calls()
	-- 			end,
	-- 		},
	-- 		{
	-- 			"<leader>ss",
	-- 			function()
	-- 				require("telescope.builtin").lsp_dynamic_workspace_symbols()
	-- 			end,
	-- 		},
	-- 		{
	-- 			"gd",
	-- 			function()
	-- 				require("telescope.builtin").lsp_definitions()
	-- 			end,
	-- 		},
	-- 		{
	-- 			"gi",
	-- 			function()
	-- 				require("telescope.builtin").lsp_implementations()
	-- 			end,
	-- 		},
	-- 	},
}
